### ISSUE TITLE
No Exceptions?

### ISSUE THREAD

**Issue by thknx** [injae/serdepp#55]
Hi,

Is is possible to use library with disabling exceptions? (-fno-exceptions)

(Out project restricts us to use exceptions)

**Comment by injae** [comment]
For serdepp's own exceptions 
I think it is possible to change the code in a 'throw exception -> std::expect' fashion, or replace it with 'throw -> std::abort', which [nolhmann::json](https://github.com/nlohmann/json/blob/58d6aa58316a84fc770bdd0409934cdfdf0697dc/include/nlohmann/detail/macro_scope.hpp#L177) uses, or in some other way.

However, since serdepp depends on adapters for its serialization and deserialization logic, I think that even if it supports 'No Exception', it will depend on the adapter library you use.
